language: node_js
node_js:
- '8'
- '10'
before_script:
- "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
- "chmod +x ./cc-test-reporter"
- "./cc-test-reporter before-build"
deploy:
  provider: npm
  email: admin@cmr1.com
  on:
    tags: true
    repo: cmr1/node-logger
  api_key:
    secure: ohrzC4hJyIyA535P1d+ivKge6OsOq9B57fx8p60tPgDtJB4L4lQPumYm0U5J+uXwJA2jB6M4R0w1QfLjJzF9DsJpArBPFkGZ8a+0jmcIkqWti0/kMSO5lOe//NNEO3zI4FyEUaixhoDUGtIR6ToRLIHm/czcN5i+0ZTZAd6w9Qxq3K26F0wg2lwiYb5E2sh1mQfo9UqjuglKos9ghyEjD52sy42z3qzZ9r8aRX8OugQBV7zZXLQ3Xh90Vavf3jvfWSKpFjHVTejjWsKALTV6XLAnMuyBHWlbN+y4v+K8LvVxiysNnc0WIb6IdvHA7BSDc8h94p/wenMYHHLTGXI0lW5OUcYPvm4M+jYG+LcrUInNYuCKSHgd7zwlWLbb4f3xFH++L+QAvNQXQDhHnXa2ZB88zEBtclGBUx9GfdsStBhtBrZZZd19SD3mbdzo2wdHvio/jNV05tEtkTq+P4q/4nmkqPYmFzjYW49XZSJaPf63xniQd358G18rkNHYjllYMPPxOi0CKLGadSADVYKlNY91nGDzqwO2rWbNkWCDnFZAb1eGd7QYLNHikjxjXLLXYvekT2Do94hbbxamdmgTD7gVHJm1UPzAA3kbBTeP2b2yoAb96ECqhNHflylKsn1tR1e8uWk/PweTj8QjjYr2cqqOaLkQ0qsk0cyCZejxqQU=
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  slack:
    secure: ZOKCXOnoC2mKTKJMDoq9zTymOYPzqb6OFOUUH7qYexw4B6BDu/HpF7f62ljz68T9aDPGXNPvMuSuAb5R7zbLP5kzbc72iRN41uDCmbCT3QZQXbRGMG9sBgL11+c799ztcvI3w5YZv0VspLznXQZSmh8fqdlLok0mOnZUUq5314V6FTNWE+OQoga7snUZCsyoxVCtn7L4CThWfZKSrYbVRyQMR1NK+tkBIT6yu2mXmTVjI0RET0LtA9oqR7cQvZimnBaxKjK8Ou3TQa96pBLYkOfcJgTnKU7uSw1zboPvUJSNRyM4XputdDno1ctv1JjobRoXzGHgsqqd2UAVApsueUcwORx1nv8+VWNy5cJNhW8nIR6CmvgVnLbsLYiRQ7AHR/RSzXJz67NyM9p60DMkrWAZ/OMKq5xUV2crRdqCHpb9XvcwkZQw5Hb1KoaM4U20mQMxZvsA5Bu9++qSL47CddmMwDojCEMstvOeCwGsY0JYW0pAol2+HXH/plK4useGSjGm+QroYvzH6g5iAKiNkyQLu7hbIllxe3c78dP8YokPDm9+sYBCbVm+Oy0kfUll9LC17b2NznLhSP8ztTgr+7BYm0/wRN75o2H29RaUTMLHvYhbcyn459N3PBM2D8AoWW7/nlUYlBeFOg2yYGGfOu2WHdvwh73kTDnG/KQqMbM=
env:
  global:
    secure: F3Wn+2nWshFXpUsAsaoNnNH5jQjVM+0AxDqZfxmZT6NMXzur7mRLbHe5q2OSAR7O5SlRQd8Ap2W9K1dxc6uQjdvDVJzifs+zfFC3pw8pPMb71SpOnxErwnxPtcobyF967J0uugP+BNk4BklegzKnIDcsEFsQ2tdObnYzAMpUutJlewR1PdCZ1BYIn/dFzt8WG+SVDfji5FUdzGgFtz2acVCuw6X7EyUpXziBpIXcIJ6yguoe4zrQSjr3sjU9w/LaAEUVjBeClJ8MXWKuUWdOzQw83Xp6HO/V02ig/nJ+SVvS31zE4H+MzySH9WPS40ttMzZDb5rgaXm81p9cg1Lax4YqSYyCDYGj5zgRFb/0ObxnGPAucUr329+duWNbheeInn1GbYbAcnBGMrycKu5bH1wXqSqx1A8e9UrTNIUwmBGjtcbAaFobMLLCiTfucssT/FIEs73f/erBW2TUkYpF2mK/oj1e6Q726CNfxD96yrpym/ttUm+fgL4ojq6j5HpY+sPjgqtJMcXPFenBFWmkPWIUU3Z+FlKzh2/QMlgkZENgs+p+SKD1puncWiHJZSog2HYStddXHKg8xkdM6yCkBZPvOxKwaHVb6untHMGBiE0dlXyiK7CFZ6lNkkp/XH9OrV+8fxCJXlzWdFgyKy8l4bJGGwu3Gek4E/B0UQK3ZLo=
