language: node_js
node_js:
- '8'
- '10'
deploy:
  provider: npm
  email: admin@cmr1.com
  on:
    tags: true
    repo: cmr1/node-logger
  api_key:
    secure: ohrzC4hJyIyA535P1d+ivKge6OsOq9B57fx8p60tPgDtJB4L4lQPumYm0U5J+uXwJA2jB6M4R0w1QfLjJzF9DsJpArBPFkGZ8a+0jmcIkqWti0/kMSO5lOe//NNEO3zI4FyEUaixhoDUGtIR6ToRLIHm/czcN5i+0ZTZAd6w9Qxq3K26F0wg2lwiYb5E2sh1mQfo9UqjuglKos9ghyEjD52sy42z3qzZ9r8aRX8OugQBV7zZXLQ3Xh90Vavf3jvfWSKpFjHVTejjWsKALTV6XLAnMuyBHWlbN+y4v+K8LvVxiysNnc0WIb6IdvHA7BSDc8h94p/wenMYHHLTGXI0lW5OUcYPvm4M+jYG+LcrUInNYuCKSHgd7zwlWLbb4f3xFH++L+QAvNQXQDhHnXa2ZB88zEBtclGBUx9GfdsStBhtBrZZZd19SD3mbdzo2wdHvio/jNV05tEtkTq+P4q/4nmkqPYmFzjYW49XZSJaPf63xniQd358G18rkNHYjllYMPPxOi0CKLGadSADVYKlNY91nGDzqwO2rWbNkWCDnFZAb1eGd7QYLNHikjxjXLLXYvekT2Do94hbbxamdmgTD7gVHJm1UPzAA3kbBTeP2b2yoAb96ECqhNHflylKsn1tR1e8uWk/PweTj8QjjYr2cqqOaLkQ0qsk0cyCZejxqQU=
notifications:
  slack:
    secure: ZOKCXOnoC2mKTKJMDoq9zTymOYPzqb6OFOUUH7qYexw4B6BDu/HpF7f62ljz68T9aDPGXNPvMuSuAb5R7zbLP5kzbc72iRN41uDCmbCT3QZQXbRGMG9sBgL11+c799ztcvI3w5YZv0VspLznXQZSmh8fqdlLok0mOnZUUq5314V6FTNWE+OQoga7snUZCsyoxVCtn7L4CThWfZKSrYbVRyQMR1NK+tkBIT6yu2mXmTVjI0RET0LtA9oqR7cQvZimnBaxKjK8Ou3TQa96pBLYkOfcJgTnKU7uSw1zboPvUJSNRyM4XputdDno1ctv1JjobRoXzGHgsqqd2UAVApsueUcwORx1nv8+VWNy5cJNhW8nIR6CmvgVnLbsLYiRQ7AHR/RSzXJz67NyM9p60DMkrWAZ/OMKq5xUV2crRdqCHpb9XvcwkZQw5Hb1KoaM4U20mQMxZvsA5Bu9++qSL47CddmMwDojCEMstvOeCwGsY0JYW0pAol2+HXH/plK4useGSjGm+QroYvzH6g5iAKiNkyQLu7hbIllxe3c78dP8YokPDm9+sYBCbVm+Oy0kfUll9LC17b2NznLhSP8ztTgr+7BYm0/wRN75o2H29RaUTMLHvYhbcyn459N3PBM2D8AoWW7/nlUYlBeFOg2yYGGfOu2WHdvwh73kTDnG/KQqMbM=
